[2023-12-28T09:24:28.830+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a manual__2023-12-28T09:19:41.042375+00:00 [queued]>
[2023-12-28T09:24:28.836+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_to_datalake.table_source_a manual__2023-12-28T09:19:41.042375+00:00 [queued]>
[2023-12-28T09:24:28.836+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 4
[2023-12-28T09:24:28.844+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): table_source_a> on 2023-12-28 09:19:41.042375+00:00
[2023-12-28T09:24:28.877+0000] {standard_task_runner.py:60} INFO - Started process 1258 to run task
[2023-12-28T09:24:28.882+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_to_datalake', 'table_source_a', 'manual__2023-12-28T09:19:41.042375+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/etl_to_datalake.py', '--cfg-path', '/tmp/tmp1aubmnbz']
[2023-12-28T09:24:28.884+0000] {standard_task_runner.py:88} INFO - Job 45: Subtask table_source_a
[2023-12-28T09:24:28.952+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_to_datalake.table_source_a manual__2023-12-28T09:19:41.042375+00:00 [running]> on host 64bb4a2d8189
[2023-12-28T09:24:29.029+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_to_datalake' AIRFLOW_CTX_TASK_ID='table_source_a' AIRFLOW_CTX_EXECUTION_DATE='2023-12-28T09:19:41.042375+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-28T09:19:41.042375+00:00'
[2023-12-28T09:24:29.045+0000] {logging_mixin.py:188} INFO - ----DEBUG query:
SELECT unique_key,
       complaint_description,
       SOURCE,
       DATE(last_update_date) AS partition_date
FROM `bigquery-public-data.austin_311.311_service_requests`
LIMIT 100
[2023-12-28T09:24:29.055+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-28T09:24:34.684+0000] {logging_mixin.py:188} INFO - ----DEBUG query_result: Row(('23-00447367', 'WPD - Lady Bird Lake Debris Issues', 'Spot311 Interface', datetime.date(2023, 12, 18)), {'unique_key': 0, 'complaint_description': 1, 'SOURCE': 2, 'partition_date': 3})
[2023-12-28T09:24:34.690+0000] {python.py:201} INFO - Done. Returned value was: None
[2023-12-28T09:24:34.712+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_to_datalake, task_id=table_source_a, execution_date=20231228T091941, start_date=20231228T092428, end_date=20231228T092434
[2023-12-28T09:24:34.760+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2023-12-28T09:24:34.792+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
