[2024-03-19T04:34:19.397+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_python_operator.first_task manual__2024-03-19T04:34:16.363088+00:00 [queued]>
[2024-03-19T04:34:19.407+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_python_operator.first_task manual__2024-03-19T04:34:16.363088+00:00 [queued]>
[2024-03-19T04:34:19.407+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-03-19T04:34:19.417+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): first_task> on 2024-03-19 04:34:16.363088+00:00
[2024-03-19T04:34:19.426+0000] {standard_task_runner.py:60} INFO - Started process 158 to run task
[2024-03-19T04:34:19.433+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'simple_python_operator', 'first_task', 'manual__2024-03-19T04:34:16.363088+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/simple_python_op.py', '--cfg-path', '/tmp/tmpzv6pyngo']
[2024-03-19T04:34:19.437+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask first_task
[2024-03-19T04:34:19.498+0000] {task_command.py:423} INFO - Running <TaskInstance: simple_python_operator.first_task manual__2024-03-19T04:34:16.363088+00:00 [running]> on host 24bcbe611895
[2024-03-19T04:34:20.575+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_python_operator' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T04:34:16.363088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-19T04:34:16.363088+00:00'
[2024-03-19T04:34:20.583+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/simple_python_op.py", line 16, in print_string
    df = pd.DataFrame({"msg": message})
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 709, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 481, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 115, in arrays_to_mgr
    index = _extract_index(arrays)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/internals/construction.py", line 645, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
[2024-03-19T04:34:20.599+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_python_operator, task_id=first_task, execution_date=20240319T043416, start_date=20240319T043419, end_date=20240319T043420
[2024-03-19T04:34:20.608+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 10 for task first_task (If using all scalar values, you must pass an index; 158)
[2024-03-19T04:34:20.678+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-19T04:34:20.709+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
